/* GENERATED FROM spec/values.yaml — DO NOT EDIT. Run `pnpm gen:values`. */
export const VALUES = {
  decay: {
    aMin: 0.05,
    halfLifeDays: 30,
    dormantFactor: 2,
  },
  consolidation: {
    hourUtc: 19,
    redistributeLerp: 0.6,
    radiusScope: 60,
    temporalLinkDecay: 0.97,
    semanticLinkGain: 0.01,
    spreadStrength: 6,
    gistStageRadii: [40,55,68,78],
    weakEdgeThreshold: 0.2,
    weakEdgeIdleDays: 14,
    weakEdgeFloor: 0.05,
    reknnMinAgeDays: 7,
  },
  forceSim: {
    theta: 0.9,
    repulsion: -30,
    linkDistance: 30,
    centerGravity: 0.01,
    velocityDecay: 0.6,
    alphaMin: 0.001,
    radialStrength: 0.08,
    linkStrength: 1,
    maxSpeedFactor: 2,
    alphaDecayTicks: 300,
    minDist: 1,
    minDist2: 1,
    seedRadius: 30,
    seedHeatFloor: 0.1,
  },
  connection: {
    knnK: 8,
    weightAlpha: 1,
    temporalBonusMax: 0.3,
    temporalWindowDays: 7,
    semanticWeightCap: 0.79,
    intraEntryWeight: 0.8,
    emoAlpha: 0.1,
  },
  excitability: {
    tauHours: 6,
    wExc: 0.25,
    biasedK: 5,
    inhibitDecay: 0.5,
  },
  reshape: {
    peThreshold: 0.15,
    baseStep: 0.22,
    minBrightStep: 0.1,
    maxBrightStep: 0.22,
    brightnessOffsetMax: 1,
    neighborFactor: 0.4,
    hueGainDeg: 60,
    hueMaxDeg: 28,
    formGain: 0.5,
    formDeltaMax: 0.6,
    strengthRecallGain: 0.15,
    ageGain: 0.3,
    ageRefDays: 90,
  },
  memoryWeight: {
    storageBase: 1,
    emoConsolidation: 0.6,
    tau0Days: 14,
    tauStorageGain: 0.8,
  },
  rewrite: {
    stageThreshold: 2,
    debounceHours: 24,
  },
  ambient: {
    arousalGain: 0.3,
    bgBrightnessGain: 0.35,
    bgMotionGain: 0.6,
    valenceWarmGain: 0.12,
    valenceSatGain: 0.25,
  },
  recall: {
    coRecallDelta: 0.05,
    dwellMs: 2000,
  },
  extraction: {
    maxSegments: 5,
  },
  invite: {
    codeLength: 8,
    timedPresetHours: [24,168,720],
    validateDebounceMs: 400,
    charStaggerMs: 60,
    celebrateMs: 1200,
  },
  customization: {
    startingStardust: 100,
    price: {"background:vortex":30,"background:crystal":30,"background:mandala":40,"star:form:octa":25,"star:form:smooth":25,"star:form:cloudy":30,"star:form:liquid":30,"star:surface:glossy":25,"star:surface:lava":30,"star:surface:cloud":30,"star:surface:pulse":30,"self:form:cube":25,"self:form:bloom":30,"self:surface:prism":25,"self:surface:neuron":30,"synapse:form:branched":25,"synapse:form:dotted":25,"synapse:surface:beads":30,"synapse:surface:steady":25},
    free: {"background":"galaxy","star:form":"lowpoly","star:surface":"facet","self:form":"orb","self:surface":"mirror","synapse:form":"strands","synapse:surface":"flow"},
  },
  admin: {
    userListDefaultPageSize: 50,
    userListMaxPageSize: 100,
  },
  radialLayout: {
    repulsion: -18,
    linkDistance: 14,
    radialStrength: 0.1,
    rMin: 6,
    rMax: 80,
    connDriftAlpha: 0.6,
    connWeightTerm: 0.5,
    satGamma: 0.6,
    driftStepRad: 0.08,
  },
  starRender: {
    sizeBase: 0.6,
    sizeRange: 1.4,
    birthDurS: 1.2,
    burstDurS: 1.6,
    burstBaseScale: 2.5,
    burstGrow: 16,
    burstFadeGain: 1.2,
  },
  starForm: {
    displaceAmp: 0.13,
    detailAmp: 0.06,
    asymmetry: 0.22,
    stageSimplify: 0.75,
  },
  starLighting: {
    selfIntensity: 0.9,
    selfDistance: 50,
    selfDecay: 0.7,
    litAlbedoGain: 0.4,
    litMix: 1,
    ambientFill: 0.4,
    backdropLightDir: [0.6,0.7,0.4],
    backdropLightIntensity: 0.7,
    recallLightBackOffset: 6,
    recallLightUpOffset: 2,
  },
  resonanceRing: {
    baseScale: 2.6,
    pulseScale: 0.12,
    pulseSpeed: 1.4,
    opacityMin: 0.22,
    opacityAmp: 0.42,
  },
  focus: {
    dim: 0.12,
    boost: 1.3,
    synapseDimStar: 0.1,
    synapseDimDiary: 0.12,
  },
  synapse: {
    widthThinPx: 1,
    widthThickPx: 4,
    thickThreshold: 0.5,
    alphaMin: 0.15,
    vitalityCap: 0.12,
    vitalityLogDiv: 4,
    pulseFreq: 3,
    lineWidthPx: 2,
    twistTurns: 2.5,
    flowSpeed: 0.22,
    strandBounds: [0.35,0.6,0.85],
    strandCount: [2,4,6,9],
    strandRadius: [0.01,0.018,0.028,0.04],
    strandBright: [0.2,0.32,0.45,0.6],
    strandOpacity: [0.5,0.62,0.72,0.82],
  },
  bloom: {
    strength: 0.9,
    radius: 0.5,
    threshold: 0.1,
  },
  cosmos: {
    sceneDpr: 1.5,
    fpsCap: 30,
    fluidOctaves: 3,
    backBrightness: 0.5,
    twinkleCount: 90,
    qualityLowMaxCores: 4,
  },
  selfStar: {
    radius: 5,
  },
  layout: {
    rekickThreshold: 0.5,
    rekickAlpha: 0.3,
  },
  starDust: {
    opacityDimmed: 0.14,
    opacityNormal: 0.5,
  },
  overlay: {
    tintStrength: 0.16,
    skyOffset: 66,
  },
  resonanceBridge: {
    flowSpeed: 0.16,
    baseGlow: 0.5,
    peakGlow: 1,
    focusBoost: 1.7,
    lineWidthPx: 3,
  },
  gesture: {
    dragDeadzonePx: 8,
    closeThrustDeadzonePx: 6,
    closeThrustFullPx: 90,
    closeLookSensitivity: 2.2,
    farPanSpeed: 1,
    farZoomScrubDeadzonePx: 8,
    farZoomScrubSpeed: 0.004,
    doubleTapMs: 300,
    doubleTapMaxDistPx: 24,
    farRotateSpeed: 2.4,
    farDamp: 9,
    farZoomSpeed: 0.12,
  },
  wayfinding: {
    frameMargin: 1.3,
    frameMinDistance: 12,
  },
  wobble: {
    amp: 1,
    freq: [[0.24,0.2],[0.2,0.26],[0.16,0.32]],
    phase: [1.7,3.1,5.3],
  },
  demoLinking: {
    knnK: 5,
    simTau: 0.4,
    coRecallBump: 0.1,
    coRecallBase: 0.5,
    addSameDayLinks: 2,
    addSameMoodLinks: 1,
    addTemporalWeight: 0.55,
    addSemanticWeight: 0.6,
    addExcitabilityWeight: 0.66,
  },
  demoConsolidation: {
    gistAgeDays: 30,
    gistFormSimplify: 0.18,
    weakEdgeThreshold: 0.7,
    weakEdgeFloor: 0.12,
  },
  demoOverlay: {
    maxBridges: 4,
  },
  demoFreeMode: {
    randomStarMin: 1,
    randomStarMax: 5,
  },
  demoTour: {
    rotateThresholdRad: 0.9,
    zoomRatioThreshold: 0.25,
    lookThresholdRad: 0.9,
    thrustDistanceThreshold: 8,
  },
} as const
