/* GENERATED FROM spec/values.yaml - DO NOT EDIT. Run `pnpm gen:values`. */
export const VALUES = {
  clientCache: {
    defaultStaleMs: 30000,
    defaultGcMs: 300000,
    defaultRetryCount: 1,
    optimisticRollbackMs: 10000,
  },
  errors: {
    toastAutoDismissMs: 6000,
  },
  authSession: {
    accessTokenRefreshSkewMs: 60000,
  },
  supabaseAuth: {
    jwksCacheTtlMs: 600000,
    jwksMissRefreshIntervalMs: 60000,
  },
  account: {
    nicknameMinLength: 2,
    nicknameMaxLength: 24,
    inviteLinkTtlDays: 7,
    withdrawalRetentionDays: 30,
  },
  rendering: {
    activeSkin: "emotion",
    maxPixelRatio: 2,
    adaptiveDprWindowSeconds: 1.5,
    adaptiveDprDownFps: 45,
    adaptiveDprUpFps: 57,
    adaptiveDprStep: 0.25,
    adaptiveDprMaxFlipflops: 2,
    coordinatePublicationEpsilon: 0.002,
    toneMapping: "neutral",
    toneMappingExposure: 1,
    emotionSkyExposure: 0.62,
    emotionSkyOpacity: {"grainient":0.74,"grainstorm":0.82,"iridescence":0.76,"soft_aurora":0.86,"liquid_ether":0.74,"prismatic_burst":0.9,"plasma_wave":0.92,"ferrofluid":0.92,"floating_lines":0.88,"evil_eye":0.92,"lightfall":0.92,"pixel_blast":0.94},
    emotionSkyHeadroom: {"grainient":0.72,"grainstorm":0.66,"iridescence":0.7,"soft_aurora":0.58,"liquid_ether":0.7,"prismatic_burst":0.8,"plasma_wave":0.82,"ferrofluid":0.68,"floating_lines":0.84,"evil_eye":0.8,"lightfall":0.84,"pixel_blast":0.88},
    starSizeMin: 0.7,
    starSizeMax: 2.4,
    starBrightnessMin: 0.15,
    starBrightnessMax: 1,
    filamentWidthMin: 0.04,
    filamentWidthMax: 0.35,
    filamentBrightnessMin: 0.12,
    filamentBrightnessMax: 0.85,
    cellStarPointSize: 0.26,
    starShapeTriangleBudget: 5120,
    starFieldCount: 2600,
    starFieldCountMobile: 1000,
    starFieldRadius: 520,
    starFieldRadiusMobile: 520,
    starFieldMoteDetail: 0,
    latentStarCount: 1800,
    latentStarCountMobile: 700,
    latentStarSegments: 6,
    latentStarSegmentsMobile: 4,
    latentFieldRadius: 56,
    latentStarSize: 0.12,
    awakenCapacity: 32,
    gistStarSizeMin: 0.55,
    gistStarSizeMax: 1.8,
    gistStarDiffuse: 0.55,
    gistRiseLayerFog: 0.35,
  },
  nebula: {
    bleedRadiusCoefficient: 6,
    minBleedRadius: 2,
    falloffExponent: 4.5,
    maxContributors: 96,
    fieldResolutionWeb: 24,
    fieldResolutionMobile: 10,
    baseIntensity: 0.42,
  },
  ai: {
    embeddingDim: 1024,
    perCallTokenCap: 7000,
    dailyCallCap: 200,
    jobMaxAttempts: 5,
    jobBackoffBaseMs: 60000,
    jobLeaseMs: 300000,
    jobMaxClaims: 20,
    jobTerminalRetentionDays: 30,
  },
  emotion: {
    moodValence: {"joy":0.82,"calm":0.62,"sad":-0.78,"anger":-0.76,"fear":-0.82,"love":0.9,"neutral":0,"excitement":0.78,"gratitude":0.76,"relief":0.68,"stress":-0.7,"tired":-0.55,"emptiness":-0.68},
    moodArousal: {"joy":0.72,"calm":0.22,"sad":0.28,"anger":0.86,"fear":0.88,"love":0.66,"neutral":0.5,"excitement":0.9,"gratitude":0.38,"relief":0.3,"stress":0.78,"tired":0.18,"emptiness":0.16},
    arousalStrengthMin: 0.35,
    arousalStrengthMax: 0.75,
    defaultIntensity: 0.7,
  },
  palette: {
    axisWarnValenceThreshold: 0.6,
    recommendationCount: 5,
    popularPresetCount: 3,
    hueBucketDegrees: 30,
    nearNeutralChromaMax: 0.04,
    similarDeltaEMin: 0.05,
    glareLuminanceMax: 0.55,
    dimLuminanceMin: 0.21,
    onboardingFieldRadius: 18,
  },
  encode: {
    minMemories: 2,
    maxMemories: 5,
    minSemanticNeurons: 1,
    maxReviseRetries: 3,
    maxOutputTokens: 6000,
    sourceTextMinCoverage: 0.9,
    sourceTextMaxRepairedRatio: 0.1,
    sourceTextMaxRepairEditDistance: 3,
    dedupSimilarityThreshold: 0.85,
    dedupTopK: 8,
    dedupBodyMatchLimit: 32,
    activationWeight: 1,
  },
  synapse: {
    potentiationRate: 0.2,
    strengthCap: 1,
    initialSameMemory: 0.32,
    initialSharedNeuron: 0.2,
    initialTemporal: 0.08,
    strengthDecayPerDay: 0.015,
    temporalWindowDays: 3,
    temporalBonus: 0.1,
  },
  semantic: {
    gistUnitsPerStage: 10,
  },
  reconsolidation: {
    recallStrengthGain: 0.15,
    neighborSlowDays: -2,
    neighborSpeedDays: 3,
    neighborSpeedThreshold: 2,
  },
  consolidation: {
    downscaleFactor: 0.05,
    downscaleFloor: 0.05,
    downscaleWeakBias: 2,
    replayNeighborHops: 1,
  },
  forgetting: {
    brightnessDecayPerDay: 0.02,
    brightnessFloor: 0.15,
    stageIntervalDays: 30,
    stageWordRemovalRatios: [0.2,0.4,0.6,0.85],
    arousalSlowCoefficient: 1,
    connectionSlowCoefficient: 1,
    costWeightFloor: 1,
    costWeightCap: 4,
    costWeightCurve: 2,
  },
  twinkle: {
    smallDailyAmount: 100,
    recallBaseCost: 5,
    recallDepthCoefficient: 10,
    recallMaxCost: 40,
    gistBaseCost: 10,
    gistStageDiscount: 3,
    gistMinCost: 3,
    earnWrite: 100,
    earnInviteInviter: 500,
    earnInviteInvitee: 500,
    earnSignupBonus: 500,
    inviteRewardMaxPerInviter: 10,
    ledgerPageSize: 50,
    adminGrantMax: 100000,
  },
  store: {
    backgroundPrice: 300,
    starShaderPrice: 600,
  },
  achievement: {
    rewardTier1: 50,
    rewardTier2: 150,
    rewardTier3: 400,
    recoveryDecayStageMin: 2,
    claimToastMs: 4000,
    unlockNoticeMax: 2,
  },
  admin: {
    userListPageSize: 50,
  },
  forceSim: {
    charge: 0.035,
    linkDistance: 20,
    centerStrength: 0.008,
    repulsion: 5,
    tickAlphaDecay: 0.022,
    velocityDamping: 0.62,
    minAlpha: 0.02,
    hippocampusZMin: 0,
    hippocampusZMax: 18,
    neocortexZMin: 27,
    neocortexZMax: 45,
    seed: 190019,
  },
  diaryReader: {
    pageSize: 20,
    searchMinQueryLength: 2,
    calendarMonthPageSize: 31,
    calendarStaleMs: 10000,
    calendarPrefetchMonths: 1,
    calendarWeekStartDay: 0,
    bodyPreviewLength: 100,
    rowMoodDotMax: 4,
    infiniteScrollRootMarginPx: 400,
    rowEstimateHeightPx: 114,
    rowOverscan: 4,
    rowGapPx: 8,
    rowMinWidthPx: 288,
    infiniteScrollEndThreshold: 0.5,
    searchDebounceMs: 300,
  },
  deletion: {
    contributionWeakenAmount: 0.15,
  },
  release: {
    softDeleteRetentionDays: 30,
  },
  sequence: {
    captionDwellMs: 4500,
    highlightPulseMs: 1800,
  },
  demo: {
    timeTravelMonthDays: 30,
    maskLiftLingerMs: 2400,
  },
  landing: {
    walkthroughFadeSpanDays: 150,
    walkthroughMirrorRecalls: 5,
  },
} as const
