/* GENERATED FROM spec/values.yaml - DO NOT EDIT. Run `pnpm gen:values`. */
export const VALUES = {
  clientCache: {
    defaultStaleMs: 30000,
    defaultGcMs: 300000,
    defaultRetryCount: 1,
    optimisticRollbackMs: 10000,
  },
  authSession: {
    accessTokenRefreshSkewMs: 60000,
  },
  supabaseAuth: {
    jwksCacheTtlMs: 600000,
    jwksMissRefreshIntervalMs: 60000,
  },
  rendering: {
    activeSkin: "aurora",
    maxPixelRatio: 2,
    instanceBucketSize: 4096,
    starSizeMin: 0.9,
    starSizeMax: 3.2,
    starBrightnessMin: 0.15,
    starBrightnessMax: 1,
    filamentWidthMin: 0.04,
    filamentWidthMax: 0.35,
    filamentBrightnessMin: 0.12,
    filamentBrightnessMax: 0.85,
    cellStarPointSize: 0.35,
    latentStarCount: 800,
    latentStarCountMobile: 300,
    latentFieldRadius: 34,
    latentStarSize: 0.14,
    awakenCapacity: 32,
    gistStarSizeMin: 0.7,
    gistStarSizeMax: 2.4,
    gistStarDiffuse: 0.55,
    gistRiseLayerFog: 0.35,
  },
  nebula: {
    bleedRadiusCoefficient: 12,
    minBleedRadius: 3,
    falloffExponent: 3.5,
    maxContributors: 96,
    fieldResolutionWeb: 24,
    fieldResolutionMobile: 10,
    baseIntensity: 0.3,
  },
  ai: {
    embeddingDim: 1024,
    perCallTokenCap: 1200,
    dailyCallCap: 200,
    jobMaxAttempts: 5,
    jobBackoffBaseMs: 60000,
    jobLeaseMs: 300000,
    jobMaxClaims: 20,
  },
  emotion: {
    moodValence: {"joy":0.82,"calm":0.62,"sad":-0.78,"anger":-0.76,"fear":-0.82,"love":0.9,"neutral":0,"excitement":0.78,"gratitude":0.76,"relief":0.68,"stress":-0.7,"tired":-0.55,"emptiness":-0.68},
    moodArousal: {"joy":0.72,"calm":0.22,"sad":0.28,"anger":0.86,"fear":0.88,"love":0.66,"neutral":0.5,"excitement":0.9,"gratitude":0.38,"relief":0.3,"stress":0.78,"tired":0.18,"emptiness":0.16},
    arousalStrengthMin: 0.35,
    arousalStrengthMax: 0.75,
    defaultIntensity: 0.7,
  },
  encode: {
    minMemories: 2,
    maxMemories: 5,
    minSemanticNeurons: 1,
    maxReviseRetries: 3,
    maxOutputTokens: 1000,
    dedupSimilarityThreshold: 0.85,
    dedupTopK: 8,
    dedupBodyMatchLimit: 32,
    activationWeight: 1,
  },
  synapse: {
    potentiationRate: 0.2,
    strengthCap: 1,
    initialSameMemory: 0.32,
    initialSharedNeuron: 0.2,
    initialTemporal: 0.08,
    strengthDecayPerDay: 0.015,
    temporalWindowDays: 3,
    temporalBonus: 0.1,
  },
  semantic: {
    gistUnitsPerStage: 10,
  },
  reconsolidation: {
    recallStrengthGain: 0.15,
    neighborSlowDays: -2,
    neighborSpeedDays: 3,
    neighborSpeedThreshold: 2,
  },
  consolidation: {
    downscaleFactor: 0.05,
    downscaleFloor: 0.05,
    downscaleWeakBias: 2,
    replayNeighborHops: 1,
  },
  forgetting: {
    brightnessDecayPerDay: 0.02,
    brightnessFloor: 0.15,
    stageIntervalDays: 30,
    stageWordRemovalRatios: [0.2,0.4,0.6,0.85],
    arousalSlowCoefficient: 1,
    connectionSlowCoefficient: 1,
    costWeightFloor: 1,
    costWeightCap: 4,
    costWeightCurve: 2,
  },
  forceSim: {
    charge: 0.035,
    linkDistance: 12,
    centerStrength: 0.018,
    repulsion: 2.4,
    tickAlphaDecay: 0.022,
    velocityDamping: 0.62,
    minAlpha: 0.02,
    hippocampusZMin: 0,
    hippocampusZMax: 10,
    neocortexZMin: 15,
    neocortexZMax: 25,
    seed: 190019,
  },
} as const
