package account

import "errors"

var (
	ErrScopeRequired               = errors.New("account behavior requires authenticated user scope")
	ErrStoreRequired               = errors.New("account service requires a store")
	ErrDirectoryRequired           = errors.New("account service requires an account directory")
	ErrInviteGranterRequired       = errors.New("account service requires an invite reward granter")
	ErrSignupBonusGranterRequired  = errors.New("account service requires a signup bonus granter")
	ErrWithdrawalStoreRequired     = errors.New("account service requires a withdrawal store")
	ErrWithdrawalSchedulerRequired = errors.New("account service requires a withdrawal sweep scheduler")
	ErrCredentialDirectoryRequired = errors.New("account service requires a credential directory")
	ErrPurgersRequired             = errors.New("account service requires at least one user-data purger")
	ErrPurgerNameRequired          = errors.New("account user-data purger requires a name")
	ErrDuplicatePurger             = errors.New("account user-data purger names must be unique")
	ErrNotProvisioned              = errors.New("account profile is not provisioned")
	ErrSignupRequired              = errors.New("account signup is required")
	ErrNotWithdrawn                = errors.New("account is not withdrawn")
	ErrRestoreWindowExpired        = errors.New("account restore window expired")
	ErrNicknameInvalid             = errors.New("account nickname is invalid")
	ErrTimezoneInvalid             = errors.New("account timezone is invalid")
	ErrLocaleInvalid               = errors.New("account locale is invalid")
	ErrMoodInvalid                 = errors.New("account mood is invalid")
	ErrColorInvalid                = errors.New("account color is invalid")
	ErrAuthProviderInvalid         = errors.New("account auth provider is invalid")
	ErrInviteLinkUnavailable       = errors.New("account invite link is unavailable")
	ErrInviteTokenInvalid          = errors.New("account invite token is invalid")
	ErrInviteTokenExpired          = errors.New("account invite token is expired")
	ErrInviteNotEligible           = errors.New("account invite is not eligible for settlement")
)
