package rpc

const (
	reasonDiaryDateInvalid           = "MEMORY_DIARY_DATE_INVALID"
	reasonEncodeInputRequired        = "MEMORY_ENCODE_INPUT_REQUIRED"
	reasonLaunchInvalidMemories      = "MEMORY_LAUNCH_INVALID_MEMORIES"
	reasonRecallInputRequired        = "MEMORY_RECALL_INPUT_REQUIRED"
	reasonViewSemanticInputRequired  = "MEMORY_VIEW_SEMANTIC_INPUT_REQUIRED"
	reasonProvenanceInputRequired    = "MEMORY_PROVENANCE_INPUT_REQUIRED"
	reasonExportFormatRequired       = "MEMORY_EXPORT_FORMAT_REQUIRED"
	reasonDiaryPageTokenInvalid      = "MEMORY_DIARY_PAGE_TOKEN_INVALID"
	reasonReleaseInputRequired       = "MEMORY_RELEASE_INPUT_REQUIRED"
	reasonLetGoInvalidApproved       = "MEMORY_LET_GO_INVALID_APPROVED"
	reasonOperationIDRequired        = "MEMORY_OPERATION_ID_REQUIRED"
	reasonOperationConflict          = "MEMORY_OPERATION_CONFLICT"
	reasonRecallMemoryNotFound       = "MEMORY_RECALL_MEMORY_NOT_FOUND"
	reasonRecallNoLiveMemories       = "MEMORY_RECALL_NO_LIVE_MEMORIES"
	reasonViewSemanticMemoryNotFound = "MEMORY_VIEW_SEMANTIC_MEMORY_NOT_FOUND"
	reasonProvenanceMemoryNotFound   = "MEMORY_PROVENANCE_MEMORY_NOT_FOUND"
	reasonReleaseMemoryNotFound      = "MEMORY_RELEASE_MEMORY_NOT_FOUND"
	reasonReleaseNoLiveMemories      = "MEMORY_RELEASE_NO_LIVE_MEMORIES"
	reasonRestoreNotReleased         = "MEMORY_RESTORE_NOT_RELEASED"
	reasonRecallMemoryUnavailable    = "MEMORY_RECALL_MEMORY_UNAVAILABLE"
	reasonViewSemanticStageNotRisen  = "MEMORY_VIEW_SEMANTIC_STAGE_NOT_RISEN"
	reasonReleaseMemoryUnavailable   = "MEMORY_RELEASE_MEMORY_UNAVAILABLE"
	reasonAlreadyReleased            = "MEMORY_ALREADY_RELEASED"
	reasonRestoreWindowExpired       = "MEMORY_RESTORE_WINDOW_EXPIRED"
	reasonSyncConsentRequired        = "MEMORY_SYNC_CONSENT_REQUIRED"
	reasonInsufficientTwinkle        = "MEMORY_INSUFFICIENT_TWINKLE"
	reasonEncodeRetryExhausted       = "MEMORY_ENCODE_RETRY_EXHAUSTED"
	reasonScopeRequired              = "MEMORY_SCOPE_REQUIRED"
)
