#!/usr/bin/env node
// Emits packages/ui/src/theme.gen.css from the canonical token source
// (packages/ui/src/tokens.ts) as a Tailwind v4 `@theme` block. Both apps load it:
// web through @tailwindcss/vite, mobile through NativeWind. The TS map stays the
// single source — never hand-edit the generated CSS (check:gen enforces freshness).
import { writeFileSync } from 'node:fs'
import { join } from 'node:path'

import { ok, repoRoot, section } from './lib.mjs'

const { tokens, CSS_TOKEN_GROUPS } = await import(join(repoRoot, 'packages/ui/src/tokens.ts'))

const lines = []
for (const group of CSS_TOKEN_GROUPS) {
  for (const [key, value] of Object.entries(tokens[group])) {
    lines.push(`  --${group}-${key}: ${value};`)
  }
}

const css = `/* Generated by scripts/gen-tokens.mjs from packages/ui/src/tokens.ts. Do not edit. */
@theme {
${lines.join('\n')}
}
`

const outPath = join(repoRoot, 'packages/ui/src/theme.gen.css')
writeFileSync(outPath, css)

section('design tokens')
ok(`wrote ${lines.length} token(s) to packages/ui/src/theme.gen.css`)
