#!/usr/bin/env node
// Emits packages/ui/src/theme.gen.css from the canonical token source
// (packages/ui/src/tokens.ts) as a Tailwind v4 `@theme` block. Both apps load it:
// web through @tailwindcss/vite, mobile through NativeWind. The TS map stays the
// single source — never hand-edit the generated CSS (check:gen enforces freshness).
import { writeFileSync } from 'node:fs'
import { join } from 'node:path'

import { ok, repoRoot, section } from './lib.mjs'

const { tokens, CSS_TOKEN_GROUPS } = await import(join(repoRoot, 'packages/ui/src/tokens.ts'))
const { themes } = await import(join(repoRoot, 'packages/ui/src/palette.ts'))

// Default @theme: every token group. `color` is the active theme; the other groups are
// theme-invariant. Tailwind emits color utilities as `var(--color-*)`, so overriding those
// variables under a `data-theme` subtree re-skins the UI at runtime with no rebuild.
const themeLines = []
for (const group of CSS_TOKEN_GROUPS) {
  for (const [key, value] of Object.entries(tokens[group])) {
    themeLines.push(`  --${group}-${key}: ${value};`)
  }
}

// One `--color-*` override block per theme (a theme = a universe: aurora · ember).
const themeBlocks = Object.entries(themes).map(([key, palette]) => {
  const rows = Object.entries(palette).map(([role, value]) => `  --color-${role}: ${value};`)
  return `[data-theme='${key}'] {\n${rows.join('\n')}\n}`
})

const css = `/* Generated by scripts/gen-tokens.mjs from packages/ui/src/tokens.ts. Do not edit. */
@theme {
${themeLines.join('\n')}
}

${themeBlocks.join('\n\n')}
`

const outPath = join(repoRoot, 'packages/ui/src/theme.gen.css')
writeFileSync(outPath, css)

section('design tokens')
ok(
  `wrote ${themeLines.length} token(s) + ${themeBlocks.length} theme block(s) to packages/ui/src/theme.gen.css`,
)
