// Code generation: proto → Go·TS (buf) and SQL schema → Go (sqlc), all via Docker.
//
//   pnpm gen          both (whatever is configured)
//   pnpm gen:proto    buf only
//   pnpm gen:sql      sqlc only
//
// If a tool's config isn't present yet, the matching step skips with a note
// instead of failing.

import { existsSync, readFileSync, readdirSync, statSync, writeFileSync } from 'node:fs'
import { dirname, join, relative } from 'node:path'
import { run, mount, hasBufConfig, hasSqlcInputs, section, ok, note, repoRoot } from './lib.mjs'

const target = process.argv[2] // undefined | 'proto' | 'sql'
const wantProto = !target || target === 'proto'
const wantSql = !target || target === 'sql'
const bufImage = 'bufbuild/buf:1.70.0'
const sqlcImage = 'sqlc/sqlc:1.31.1'

// Run the codegen containers as the host user (Linux/WSL) so generated files are owned by the
// caller, not root — otherwise the node post-processing below (and later git/check:gen) trips
// over root-owned output. Empty on platforms without getuid (Docker Desktop maps ownership).
const dockerUser =
  typeof process.getuid === 'function'
    ? ['--user', `${process.getuid()}:${process.getgid()}`, '-e', 'HOME=/tmp']
    : []

section('codegen')
let did = false

if (wantProto) {
  if (hasBufConfig()) {
    note('buf generate (proto → Go·TS)')
    // Template lives at proto/buf.gen.yaml, module input is proto/ — both must be
    // explicit (a bare `buf generate` at repo root has no buf.gen.yaml and fails).
    run('docker', [
      'run',
      '--rm',
      ...dockerUser,
      '-v',
      mount('', '/work'),
      '-w',
      '/work',
      bufImage,
      'generate',
      '--template',
      'proto/buf.gen.yaml',
      'proto',
    ])
    const apiClientGenDir = join(repoRoot, 'packages/api-client/src/gen')
    trimGeneratedTypeScript(apiClientGenDir)
    writeApiServiceInventory(
      apiClientGenDir,
      join(repoRoot, 'packages/api-client/src/service-descriptors.gen.ts'),
    )
    ok('buf 완료')
    did = true
  } else {
    note('buf 건너뜀 — proto/ 에 .proto 계약이 아직 없음 (전송 유닛에서 추가)')
  }
}

if (wantSql) {
  if (hasSqlcInputs()) {
    note('sqlc generate (apps/api/db schema+queries → Go)')
    run('docker', [
      'run',
      '--rm',
      ...dockerUser,
      '-v',
      mount('apps/api', '/app'),
      '-w',
      '/app',
      sqlcImage,
      'generate',
    ])
    ok('sqlc 완료')
    did = true
  } else {
    note('sqlc 건너뜀 — apps/api/sqlc.yaml + db/migrations/*.sql + db/queries/*.sql 이 모두 필요함')
  }
}

if (!did) note('아직 생성할 대상 없음. 설정 추가 후 다시 실행하면 자동으로 켜져요.')

function trimGeneratedTypeScript(dir) {
  if (!existsSync(dir)) return
  for (const entry of readdirSync(dir)) {
    const path = join(dir, entry)
    if (statSync(path).isDirectory()) {
      trimGeneratedTypeScript(path)
      continue
    }
    if (!path.endsWith('.ts')) continue
    const source = readFileSync(path, 'utf8')
    const trimmed = source.replace(/\n{2,}$/u, '\n')
    if (trimmed !== source) writeFileSync(path, trimmed)
  }
}

function writeApiServiceInventory(genDir, outputPath) {
  const services = []

  for (const path of collectTypeScriptFiles(genDir)) {
    const source = readFileSync(path, 'utf8')
    for (const match of source.matchAll(/^export const ([A-Za-z_$][\w$]*): GenService</gmu)) {
      let importPath = relative(dirname(outputPath), path).replaceAll('\\', '/')
      if (!importPath.startsWith('.')) importPath = `./${importPath}`
      services.push({ importPath, name: match[1] })
    }
  }

  services.sort((left, right) =>
    `${left.importPath}:${left.name}`.localeCompare(`${right.importPath}:${right.name}`),
  )
  if (services.length === 0) {
    throw new Error(`No generated API services found under ${genDir}`)
  }

  const imports = services
    .map(({ importPath, name }) => `import { ${name} } from '${importPath}'`)
    .join('\n')
  const members = services.map(({ name }) => `  ${name},`).join('\n')
  const source = `// Code generated by scripts/gen.mjs. DO NOT EDIT.\n\n${imports}\n\nexport const apiServiceDescriptors = [\n${members}\n] as const\n`

  writeFileSync(outputPath, source)
}

function collectTypeScriptFiles(dir) {
  if (!existsSync(dir)) return []
  return readdirSync(dir).flatMap((entry) => {
    const path = join(dir, entry)
    return statSync(path).isDirectory()
      ? collectTypeScriptFiles(path)
      : path.endsWith('_pb.ts')
        ? [path]
        : []
  })
}
