// Code generated by scripts/gen.mjs. DO NOT EDIT.

import { AccountService } from './gen/cosimosi/account/v1/account_pb.ts'
import { MemoryService } from './gen/cosimosi/memory/v1/memory_pb.ts'
import { PlatformService } from './gen/cosimosi/platform/v1/platform_pb.ts'
import { TwinkleService } from './gen/cosimosi/twinkle/v1/twinkle_pb.ts'

export const apiServiceDescriptors = [
  AccountService,
  MemoryService,
  PlatformService,
  TwinkleService,
] as const
